In [ ]:
import pandas as pd
df = pd.read_csv('/content/Sales Data.csv')
print(df.head())

   Unnamed: 0  Order ID               Product  Quantity Ordered  Price Each  \
0           0    295665    Macbook Pro Laptop                 1     1700.00
1           1    295666    LG Washing Machine                 1      600.00
2           2    295667  USB-C Charging Cable                 1       11.95
3           3    295668      27in FHD Monitor                 1      149.99
4           4    295669  USB-C Charging Cable                 1       11.95

            Order Date                        Purchase Address  Month  \
0  2019-12-30 00:01:00  136 Church St, New York City, NY 10001     12
1  2019-12-29 07:03:00     562 2nd St, New York City, NY 10001     12
2  2019-12-12 18:21:00    277 Main St, New York City, NY 10001     12
3  2019-12-22 15:13:00     410 6th St, San Francisco, CA 94016     12
4  2019-12-18 12:38:00           43 Hill St, Atlanta, GA 30301     12

     Sales            City  Hour
0  1700.00   New York City     0
1   600.00   New York City     7
2    11.95   New York City    18
3   149.99   San Francisco    15
4    11.95         Atlanta    12

In [ ]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 185950 entries, 0 to 185949
Data columns (total 11 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Unnamed: 0        185950 non-null  int64
 1   Order ID          185950 non-null  int64
 2   Product           185950 non-null  object
 3   Quantity Ordered  185950 non-null  int64
 4   Price Each        185950 non-null  float64
 5   Order Date        185950 non-null  object
 6   Purchase Address  185950 non-null  object
 7   Month             185950 non-null  int64
 8   Sales             185950 non-null  float64
 9   City              185950 non-null  object
 10  Hour              185950 non-null  int64
dtypes: float64(2), int64(5), object(4)
memory usage: 15.6+ MB
None

In [ ]:
print(df.describe())

          Unnamed: 0       Order ID  Quantity Ordered     Price Each  \
count  185950.000000  185950.000000     185950.000000  185950.000000
mean     8340.388475  230417.569379          1.124383     184.399735
std      5450.554093   51512.737110          0.442793     332.731330
min         0.000000  141234.000000          1.000000       2.990000
25%      3894.000000  185831.250000          1.000000      11.950000
50%      7786.000000  230367.500000          1.000000      14.950000
75%     11872.000000  275035.750000          1.000000     150.000000
max     25116.000000  319670.000000          9.000000    1700.000000

               Month          Sales           Hour
count  185950.000000  185950.000000  185950.000000
mean        7.059140     185.490917      14.413305
std         3.502996     332.919771       5.423416
min         1.000000       2.990000       0.000000
25%         4.000000      11.950000      11.000000
50%         7.000000      14.950000      15.000000
75%        10.000000     150.000000      19.000000
max        12.000000    3400.000000      23.000000

In [ ]:
df.sample(10)

,Unnamed: 0,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address,Month,Sales,City,Hour
13058,13130,308197,Wired Headphones,1,11.99,2019-12-15 08:15:00,"231 Lincoln St, Atlanta, GA 30301",12,11.99,Atlanta,8
132931,16501,275092,Lightning Charging Cable,1,14.95,2019-10-14 09:36:00,"971 Highland St, Seattle, WA 98101",10,14.95,Seattle,9
17086,17172,312073,Lightning Charging Cable,2,14.95,2019-12-01 07:43:00,"661 Hickory St, Boston, MA 02215",12,29.90,Boston,7
127977,11521,270357,Flatscreen TV,1,300.00,2019-10-21 13:01:00,"490 Forest St, Los Angeles, CA 90001",10,300.00,Los Angeles,13
134889,18469,276973,34in Ultrawide Monitor,1,379.99,2019-10-09 18:40:00,"319 Cherry St, Los Angeles, CA 90001",10,379.99,Los Angeles,18
82357,11993,248133,USB-C Charging Cable,1,11.95,2019-08-21 08:42:00,"296 Church St, Los Angeles, CA 90001",8,11.95,Los Angeles,8
33882,8933,185088,Wired Headphones,1,11.99,2019-04-30 06:31:00,"666 Wilson St, Los Angeles, CA 90001",4,11.99,Los Angeles,6
172338,14314,236616,USB-C Charging Cable,1,11.95,2019-07-19 20:14:00,"984 Dogwood St, Boston, MA 02215",7,11.95,Boston,20
5140,5168,300580,Lightning Charging Cable,1,14.95,2019-12-17 16:30:00,"972 7th St, New York City, NY 10001",12,14.95,New York City,16
115371,16512,294574,Lightning Charging Cable,1,14.95,2019-11-17 12:19:00,"359 Dogwood St, San Francisco, CA 94016",11,14.95,San Francisco,12

In [ ]:
# Drop unnecessary columns:
df.drop(columns=['Unnamed: 0'], inplace=True)

In [ ]:
# Check for missing values
print("Missing values:\n", df.isnull().sum())

Missing values:
 Order ID            0
Product             0
Quantity Ordered    0
Price Each          0
Order Date          0
Purchase Address    0
Month               0
Sales               0
City                0
Hour                0
dtype: int64

In [ ]:
# Strip whitespace in string columns
string_cols = ['Product', 'Purchase Address', 'City']
for col in string_cols:
    df[col] = df[col].str.strip()

In [ ]:
# Validate 'Sales' column
df['Calculated Sales'] = df['Quantity Ordered'] * df['Price Each']

# Identify mismatches (rounded to 2 decimal places)
sales_mismatch = df[df['Calculated Sales'].round(2) != df['Sales'].round(2)]

# If mismatches found, fix them and notify
if not sales_mismatch.empty:
    print(f"Found {len(sales_mismatch)} mismatched 'Sales' values. Updating them...")

    # Update only the mismatched rows
    df.loc[sales_mismatch.index, 'Sales'] = df.loc[sales_mismatch.index, 'Calculated Sales']
else:
    print("No mismatched 'Sales' values found.")

No mismatched 'Sales' values found.

In [ ]:
# Extract State from 'Purchase Address'
df['State'] = df['Purchase Address'].apply(lambda x: x.split(',')[2].split()[0] if ',' in x else None)

In [ ]:
# information about the products
df['Product'].unique()

array(['Macbook Pro Laptop', 'LG Washing Machine', 'USB-C Charging Cable',
       '27in FHD Monitor', 'AA Batteries (4-pack)',
       'Bose SoundSport Headphones', 'AAA Batteries (4-pack)',
       'ThinkPad Laptop', 'Lightning Charging Cable', 'Google Phone',
       'Wired Headphones', 'Apple Airpods Headphones', 'Vareebadd Phone',
       'iPhone', '20in Monitor', '34in Ultrawide Monitor',
       'Flatscreen TV', '27in 4K Gaming Monitor', 'LG Dryer'],
      dtype=object)

In [ ]:
df[df.duplicated(subset=['Order ID','Product','Quantity Ordered','Order Date','Purchase Address'])]

,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address,Month,Sales,City,Hour,Calculated Sales,State
438,296081,Flatscreen TV,1,300.00,2019-12-30 16:52:00,"970 Sunset St, Austin, TX 73301",12,300.00,Austin,16,300.00,TX
1727,297311,Bose SoundSport Headphones,1,99.99,2019-12-07 07:30:00,"858 Willow St, Los Angeles, CA 90001",12,99.99,Los Angeles,7,99.99,CA
2812,298358,Apple Airpods Headphones,1,150.00,2019-12-04 15:57:00,"482 8th St, San Francisco, CA 94016",12,150.00,San Francisco,15,150.00,CA
3119,298657,Lightning Charging Cable,1,14.95,2019-12-01 18:22:00,"428 12th St, Atlanta, GA 30301",12,14.95,Atlanta,18,14.95,GA
3363,298883,Wired Headphones,1,11.99,2019-12-28 18:07:00,"516 Willow St, Los Angeles, CA 90001",12,11.99,Los Angeles,18,11.99,CA
...,...,...,...,...,...,...,...,...,...,...,...,...
181613,218756,AAA Batteries (4-pack),1,2.99,2019-06-11 14:54:00,"362 Hickory St, Boston, MA 02215",6,2.99,Boston,14,2.99,MA
181883,219007,AA Batteries (4-pack),1,3.84,2019-06-24 11:16:00,"42 8th St, Los Angeles, CA 90001",6,3.84,Los Angeles,11,3.84,CA
183323,220392,Lightning Charging Cable,1,14.95,2019-06-08 17:13:00,"472 8th St, Portland, ME 04101",6,14.95,Portland,17,14.95,ME
183826,220882,Lightning Charging Cable,1,14.95,2019-06-13 17:53:00,"588 Lake St, Boston, MA 02215",6,14.95,Boston,17,14.95,MA
184691,221711,Bose SoundSport Headphones,1,99.99,2019-06-15 16:36:00,"139 West St, New York City, NY 10001",6,99.99,New York City,16,99.99,NY

In [ ]:
#there are 264 duplicate rows in our dataset

In [ ]:
# verifying that there are duplicated rows
df[df['Order ID'] ==296081]

,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address,Month,Sales,City,Hour,Calculated Sales,State
437,296081,Flatscreen TV,1,300.0,2019-12-30 16:52:00,"970 Sunset St, Austin, TX 73301",12,300.0,Austin,16,300.0,TX
438,296081,Flatscreen TV,1,300.0,2019-12-30 16:52:00,"970 Sunset St, Austin, TX 73301",12,300.0,Austin,16,300.0,TX

In [ ]:
df[df['Order ID'] ==282137]

,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address,Month,Sales,City,Hour,Calculated Sales,State
102392,282137,Lightning Charging Cable,1,14.95,2019-11-13 14:40:00,"197 13th St, Los Angeles, CA 90001",11,14.95,Los Angeles,14,14.95,CA
102393,282137,Lightning Charging Cable,1,14.95,2019-11-13 14:40:00,"197 13th St, Los Angeles, CA 90001",11,14.95,Los Angeles,14,14.95,CA

In [ ]:
#dropping duplicated values:
df= df.drop_duplicates(subset=['Order ID','Product','Quantity Ordered','Order Date','Purchase Address'])

In [ ]:
# To get time
df['Time'] =df['Order Date'].str.split(' ').str.get(1)

In [ ]:
df['Order Date'] = pd.to_datetime(df['Order Date'], dayfirst = False)

In [ ]:
# changing orderdate to datetime dtype
df['Order Date'] = pd.to_datetime(df['Order Date'], dayfirst = False)

In [ ]:
# converting to day time formate
df['Time'] = pd.to_datetime(df['Time'],format = '%H:%M:%S')
df['time'] = df['Time'].dt.time

In [ ]:
# final cleaned dataset after removing duplicated values
print("\nCleaned Data Summary:")
print(df.info())

Cleaned Data Summary:
<class 'pandas.core.frame.DataFrame'>
Index: 185686 entries, 0 to 185949
Data columns (total 14 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Order ID          185686 non-null  int64
 1   Product           185686 non-null  object
 2   Quantity Ordered  185686 non-null  int64
 3   Price Each        185686 non-null  float64
 4   Order Date        185686 non-null  datetime64[ns]
 5   Purchase Address  185686 non-null  object
 6   Month             185686 non-null  int64
 7   Sales             185686 non-null  float64
 8   City              185686 non-null  object
 9   Hour              185686 non-null  int64
 10  Calculated Sales  185686 non-null  float64
 11  State             185686 non-null  object
 12  Time              185686 non-null  datetime64[ns]
 13  time              185686 non-null  object
dtypes: datetime64[ns](2), float64(3), int64(4), object(5)
memory usage: 21.3+ MB
None

In [ ]:
df.head()

,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address,Month,Sales,City,Hour,Calculated Sales,State,Time,time
0,295665,Macbook Pro Laptop,1,1700.00,2019-12-30 00:01:00,"136 Church St, New York City, NY 10001",12,1700.00,New York City,0,1700.00,NY,1900-01-01 00:01:00,00:01:00
1,295666,LG Washing Machine,1,600.00,2019-12-29 07:03:00,"562 2nd St, New York City, NY 10001",12,600.00,New York City,7,600.00,NY,1900-01-01 07:03:00,07:03:00
2,295667,USB-C Charging Cable,1,11.95,2019-12-12 18:21:00,"277 Main St, New York City, NY 10001",12,11.95,New York City,18,11.95,NY,1900-01-01 18:21:00,18:21:00
3,295668,27in FHD Monitor,1,149.99,2019-12-22 15:13:00,"410 6th St, San Francisco, CA 94016",12,149.99,San Francisco,15,149.99,CA,1900-01-01 15:13:00,15:13:00
4,295669,USB-C Charging Cable,1,11.95,2019-12-18 12:38:00,"43 Hill St, Atlanta, GA 30301",12,11.95,Atlanta,12,11.95,GA,1900-01-01 12:38:00,12:38:00

In [ ]:
# Extract only the date part
df['Date'] = df['Order Date'].dt.date
df['Date'] = pd.to_datetime(df['Date'])
df.head(1)

,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address,Month,Sales,City,Hour,Calculated Sales,State,Time,time,Date
0,295665,Macbook Pro Laptop,1,1700.0,2019-12-30 00:01:00,"136 Church St, New York City, NY 10001",12,1700.0,New York City,0,1700.0,NY,1900-01-01 00:01:00,00:01:00,2019-12-30

In [ ]:
df.rename(columns={
    'Order Date	': 'Order Date with Time'
}, inplace=True)

In [ ]:
# because there are two columns named time and we do not need Time column anymore
df.drop(['Time'],axis=1,inplace=True)

In [ ]:
# Extracting day name from order date column
df['Day Name'] = df['Order Date'].dt.day_name()

In [ ]:
df.sample(5)

,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address,Month,Sales,City,Hour,Calculated Sales,State,time,Date,Day Name
143008,147173,AA Batteries (4-pack),1,3.84,2019-01-27 17:47:00,"170 Hickory St, New York City, NY 10001",1,3.84,New York City,17,3.84,NY,17:47:00,2019-01-27,Sunday
154053,255438,Lightning Charging Cable,1,14.95,2019-09-17 21:12:00,"658 Hickory St, Atlanta, GA 30301",9,14.95,Atlanta,21,14.95,GA,21:12:00,2019-09-17,Tuesday
4554,300016,USB-C Charging Cable,1,11.95,2019-12-23 10:27:00,"204 Hickory St, Los Angeles, CA 90001",12,11.95,Los Angeles,10,11.95,CA,10:27:00,2019-12-23,Monday
95040,206192,Lightning Charging Cable,1,14.95,2019-05-22 10:40:00,"396 13th St, Atlanta, GA 30301",5,14.95,Atlanta,10,14.95,GA,10:40:00,2019-05-22,Wednesday
116214,295378,Wired Headphones,1,11.99,2019-11-09 06:48:00,"723 Cedar St, Los Angeles, CA 90001",11,11.99,Los Angeles,6,11.99,CA,06:48:00,2019-11-09,Saturday

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 185686 entries, 0 to 185949
Data columns (total 15 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Order ID          185686 non-null  int64
 1   Product           185686 non-null  object
 2   Quantity Ordered  185686 non-null  int64
 3   Price Each        185686 non-null  float64
 4   Order Date        185686 non-null  datetime64[ns]
 5   Purchase Address  185686 non-null  object
 6   Month             185686 non-null  int64
 7   Sales             185686 non-null  float64
 8   City              185686 non-null  object
 9   Hour              185686 non-null  int64
 10  Calculated Sales  185686 non-null  float64
 11  State             185686 non-null  object
 12  time              185686 non-null  object
 13  Date              185686 non-null  datetime64[ns]
 14  Day Name          185686 non-null  object
dtypes: datetime64[ns](2), float64(3), int64(4), object(6)
memory usage: 22.7+ MB

In [ ]:
df.to_csv('cleaned_data_sales.csv', index=False)